SET local check_function_bodies = off;

CREATE TABLE "public"."achievement_index" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."index_archievment_id_seq") NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "name"        text                     NOT NULL DEFAULT '''Generic Archievment'''::text,
  "description" text,
  "xp_reward"   bigint,
  "gold_reward" bigint,
  "icon_url"    text,
  CONSTRAINT "index_archievment_name_key" UNIQUE (name),
  CONSTRAINT "index_archievment_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."achievement_index"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."achievements" (
  "id"                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "acquired_at"       timestamp with time zone NOT NULL DEFAULT now(),
  "user_id"           bigint                   NOT NULL DEFAULT '0'::bigint,
  "index_id"          bigint                   NOT NULL DEFAULT '0'::bigint,
  "reward_id"         bigint,
  "archievement_icon" text,
  CONSTRAINT "achievements_pkey" PRIMARY KEY (id),
  CONSTRAINT "index_limit" CHECK ((index_id >= 0)),
  CONSTRAINT "unique_user_achievement_index" UNIQUE (user_id, index_id)
);

ALTER TABLE "public"."achievements"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."challenges" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "name"            text                     NOT NULL DEFAULT 'Challenge#000'::text,
  "chall_reward_id" bigint,
  "group_id"        bigint,
  "description"     text,
  "completed"       boolean                  NOT NULL DEFAULT false,
  "task_id"         bigint,
  "user_id"         bigint,
  "rating"          smallint                 DEFAULT '0'::smallint,
  "requirement"     text,
  CONSTRAINT "challenges_pkey" PRIMARY KEY (id),
  CONSTRAINT "chk_challenge_rating" CHECK (((rating IS NULL) OR ((rating >= 1) AND (rating <= 10))))
);

ALTER TABLE "public"."challenges"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."character_stats" (
  "id"             bigint  GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."stats_id_seq") NOT NULL,
  "hp"             bigint  NOT NULL DEFAULT '20'::bigint,
  "strength"       integer NOT NULL DEFAULT 5,
  "speed"          integer NOT NULL DEFAULT 5,
  "stamina"        integer NOT NULL DEFAULT 5,
  "wisdom"         integer NOT NULL DEFAULT 5,
  "level"          integer NOT NULL DEFAULT 1,
  "xpTotal"        bigint  NOT NULL DEFAULT '0'::bigint,
  "xpCurrent"      bigint  NOT NULL DEFAULT '0'::bigint,
  "playerName"     text    NOT NULL,
  "gold"           bigint  NOT NULL DEFAULT '0'::bigint,
  "skin_index_id"  bigint,
  "user_id"        bigint,
  "monster_beaten" integer DEFAULT 0,
  "bosses_beaten"  integer DEFAULT 0,
  "players_beaten" integer DEFAULT 0,
  "gems"           integer DEFAULT 0,
  "premium coins"  integer DEFAULT 0,
  CONSTRAINT "character_stats_user_id_key" UNIQUE (user_id),
  CONSTRAINT "chk_stats_positive_values"
    CHECK (((hp >= 0) AND (strength >= 0) AND (speed >= 0) AND (stamina >= 0) AND (wisdom >= 0) AND (level >= 1) AND ("xpTotal" >= 0) AND ("xpCurrent" >= 0) AND (gold >= 0))),
  CONSTRAINT "day_task_check" CHECK ((level > 0)),
  CONSTRAINT "stats_pkey" PRIMARY KEY (id),
  CONSTRAINT "stats_playerName_key" UNIQUE ("playerName"),
  CONSTRAINT "stats_xp_rules_check"
    CHECK
    (((((level = 1) AND ("xpTotal" = "xpCurrent")) OR ((level <> 1) AND (("xpTotal")::double precision = ((("xpCurrent")::double precision + ((level)::double precision ^
    (2)::double precision)) + ((10 * level))::double precision)))) AND
    (("xpCurrent")::double precision <= (((((level + 1))::double precision ^ (2)::double precision) + ((10 * (level + 1)))::double precision) - (((level)::double precision ^
    (2)::double precision) + ((10 * level))::double precision)))))
);

ALTER TABLE "public"."character_stats"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."equipment" (
  "id"                    bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "current_upgrade_price" bigint,
  "level"                 bigint                   NOT NULL DEFAULT 1,
  "stats"                 jsonb                    NOT NULL,
  "acquired_at"           timestamp with time zone DEFAULT now(),
  "tool_index_id"         bigint,
  "character_id"          bigint,
  "is_equiped"            boolean                  DEFAULT false,
  "nickname"              text,
  CONSTRAINT "chk_equipment_level_positive" CHECK (((level >= 1) AND (current_upgrade_price >= 0))),
  CONSTRAINT "equipment_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."equipment"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."goal" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "goal_reward_id" bigint,
  "group_id"       bigint,
  "description"    text,
  "start_date"     timestamp with time zone,
  "end_date"       timestamp with time zone,
  "user_id"        bigint,
  "rating"         smallint,
  "completed"      boolean                  DEFAULT false,
  "name"           text                     NOT NULL DEFAULT '''Goal#000'''::text,
  CONSTRAINT "check_rating" CHECK (((rating >= 1) AND (rating <= 5))),
  CONSTRAINT "chk_goal_dates" CHECK (((end_date IS NULL) OR (start_date IS NULL) OR (end_date >= start_date))),
  CONSTRAINT "chk_goal_rating" CHECK (((rating IS NULL) OR ((rating >= 1) AND (rating <= 5)))),
  CONSTRAINT "goal_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."goal"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."groups" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "user_id"     bigint                   NOT NULL DEFAULT '0'::bigint,
  "name"        text                     NOT NULL DEFAULT '''work_group#0'''::text,
  "description" text,
  CONSTRAINT "groups_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."groups"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."rewards" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "gold_reward" bigint                   NOT NULL DEFAULT '0'::bigint,
  "xp_reward"   bigint                   NOT NULL DEFAULT '0'::bigint,
  "xp_boost"    real                     NOT NULL DEFAULT '1'::real,
  "claimed_at"  timestamp with time zone,
  "user_id"     bigint,
  "gem_reward"  integer                  DEFAULT 0,
  CONSTRAINT "check_xp_boost" CHECK ((xp_boost >= (0)::double precision)),
  CONSTRAINT "chk_rewards_non_negative" CHECK (((gold_reward >= 0) AND (xp_reward >= 0) AND (xp_boost >= (0.0)::double precision))),
  CONSTRAINT "rewards_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."rewards"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."skin_index" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text                     DEFAULT '''dedault skin'''::text,
  "skin_url"   text,
  "skin_price" bigint                   DEFAULT '0'::bigint,
  CONSTRAINT "skin_index_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."skin_index"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."tasks" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."Example_id_seq") NOT NULL,
  "start_time"     timestamp with time zone NOT NULL DEFAULT now(),
  "end_time"       timestamp with time zone NOT NULL DEFAULT now(),
  "task_reward_id" bigint,
  "group_id"       bigint,
  "description"    text                     NOT NULL,
  "icon"           character varying        DEFAULT '📆'::character varying,
  "user_id"        bigint,
  "name"           text                     NOT NULL DEFAULT 'Task#000'::text,
  CONSTRAINT "Example_pkey" PRIMARY KEY (id),
  CONSTRAINT "chk_task_dates" CHECK (((end_time IS NULL) OR (start_time IS NULL) OR (end_time >= start_time))),
  CONSTRAINT "day_task_check" CHECK ((EXTRACT(day FROM start_time) = EXTRACT(day FROM end_time))),
  CONSTRAINT "time_check" CHECK (((end_time IS NULL) OR (start_time < end_time)))
);

ALTER TABLE "public"."tasks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."tool_index" (
  "id"                 bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  "max_level"          integer                  NOT NULL DEFAULT 100,
  "purchase_price"     integer,
  "base_upgrade_price" integer,
  "upgrade_stat_buffs" integer,
  "name"               text,
  "base_stats_buff"    jsonb,
  CONSTRAINT "chk_tool_prices_positive" CHECK (((purchase_price >= 0) AND (base_upgrade_price >= 0) AND (max_level >= 1))),
  CONSTRAINT "tool_index_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."tool_index"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."users" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."usuarios_id_seq") NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "username"     character varying        DEFAULT 'User#000'::character varying,
  "profile_url"  text,
  "playerName"   text,
  "email"        text                     NOT NULL DEFAULT '''Undefined'''::text,
  "task_streak"  integer                  DEFAULT 0,
  "xp_acc_boost" real                     DEFAULT 1.0,
  "inner_id"     uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_icon"    character varying        DEFAULT '⚔️'::character varying,
  "player_id"    bigint,
  CONSTRAINT "chk_users_streak_boost" CHECK (((task_streak >= 0) AND (xp_acc_boost >= (0.0)::double precision))),
  CONSTRAINT "users_inner_id_key" UNIQUE (inner_id),
  CONSTRAINT "users_playerName_key" UNIQUE ("playerName"),
  CONSTRAINT "users_player_id_key" UNIQUE (player_id),
  CONSTRAINT "usuarios_pkey" PRIMARY KEY (id),
  CONSTRAINT "usuarios_username_key" UNIQUE (username)
);

ALTER TABLE "public"."users"
  ENABLE ROW LEVEL SECURITY;

CREATE TYPE "public"."account_type" AS ENUM (
  'PREMIUM',
  'BASIC'
);

ALTER TABLE "public"."skin_index"
  ADD COLUMN "available_from" public.account_type DEFAULT 'BASIC'::public.account_type;

ALTER TABLE "public"."users"
  ADD COLUMN "account_type" public.account_type NOT NULL DEFAULT 'BASIC'::public.account_type;

CREATE TYPE "public"."difficulty_tier" AS ENUM (
  'LEGENDARY FEAT',
  'VERY HARD',
  'HARD',
  'NORMAL',
  'EASY'
);

ALTER TABLE "public"."challenges"
  ADD COLUMN "dificulty" public.difficulty_tier NOT NULL DEFAULT 'EASY'::public.difficulty_tier;

CREATE TYPE "public"."player_class" AS ENUM (
  'knight',
  'archer',
  'magician'
);

ALTER TABLE "public"."character_stats"
  ADD COLUMN "class" public.player_class NOT NULL DEFAULT 'knight'::public.player_class;

ALTER TABLE "public"."skin_index"
  ADD COLUMN "skin_class" public.player_class DEFAULT 'knight'::public.player_class;

CREATE TYPE "public"."price_unit" AS ENUM (
  'gold',
  'premium_coin',
  'gem'
);

ALTER TABLE "public"."skin_index"
  ADD COLUMN "price_unit" public.price_unit DEFAULT 'gold'::public.price_unit;

CREATE TYPE "public"."quality_tier" AS ENUM (
  'celestial',
  'legendary',
  'mythic',
  'epic',
  'rare',
  'common'
);

ALTER TABLE "public"."achievement_index"
  ADD COLUMN "tier" public.quality_tier DEFAULT 'common'::public.quality_tier;

ALTER TABLE "public"."equipment"
  ADD COLUMN "current_tool_tier" public.quality_tier NOT NULL DEFAULT 'common'::public.quality_tier;

ALTER TABLE "public"."skin_index"
  ADD COLUMN "skin_tier" public.quality_tier DEFAULT 'common'::public.quality_tier;

ALTER TABLE "public"."tool_index"
  ADD COLUMN "base_tool_tier" public.quality_tier DEFAULT 'common'::public.quality_tier;

CREATE TYPE "public"."routine_day" AS ENUM (
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
  'Once'
);

ALTER TABLE "public"."tasks"
  ADD COLUMN "routine" public.routine_day DEFAULT 'Once'::public.routine_day;

CREATE TYPE "public"."source_type" AS ENUM (
  'task',
  'challenge',
  'objective',
  'archivement',
  'boss_battle',
  'monster_battle',
  'player_battle'
);

ALTER TABLE "public"."rewards"
  ADD COLUMN "source" public.source_type;

CREATE TYPE "public"."stat" AS ENUM (
  'hp',
  'strength',
  'wisdom',
  'speed',
  'stamina'
);

CREATE TYPE "public"."task_priority" AS ENUM (
  'MAX',
  'HIGH',
  'MID',
  'LOW',
  'NULL'
);

ALTER TABLE "public"."tasks"
  ADD COLUMN "priority" public.task_priority NOT NULL;

CREATE TYPE "public"."task_status" AS ENUM (
  'PENDING',
  'IN_PROGRESS',
  'FINISHED',
  'DONE',
  'NOT_DONE'
);

ALTER TABLE "public"."tasks"
  ADD COLUMN "status" public.task_status NOT NULL DEFAULT 'PENDING'::public.task_status;

CREATE TYPE "public"."task_type" AS ENUM (
  'physical',
  'sport',
  'work',
  'social',
  'study',
  'leisure',
  'undefined'
);

ALTER TABLE "public"."tasks"
  ADD COLUMN "activity_type" public.task_type NOT NULL DEFAULT 'undefined'::public.task_type;

CREATE TYPE "public"."tool_type" AS ENUM (
  'sword',
  'wand',
  'bow',
  'helmet',
  'body_armor',
  'charm'
);

ALTER TABLE "public"."equipment"
  ADD COLUMN "type" public.tool_type;

ALTER TABLE "public"."tool_index"
  ADD COLUMN "tool_type" public.tool_type;

CREATE TYPE "public"."visibility_type" AS ENUM (
  'SHOWN',
  'HIDDEN',
  'DELETED'
);

ALTER TABLE "public"."challenges"
  ADD COLUMN "visibility" public.visibility_type DEFAULT 'SHOWN'::public.visibility_type;

ALTER TABLE "public"."goal"
  ADD COLUMN "visibility" public.visibility_type DEFAULT 'SHOWN'::public.visibility_type;

ALTER TABLE "public"."tasks"
  ADD COLUMN "visibility" public.visibility_type NOT NULL DEFAULT 'SHOWN'::public.visibility_type;

CREATE OR REPLACE FUNCTION public.get_current_user_id()
  RETURNS bigint
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  AS $function$
  SELECT id FROM public.users WHERE inner_id = auth.uid() LIMIT 1;
$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

ALTER TABLE "public"."achievements"
  ADD CONSTRAINT "achievements_index_id_fkey" FOREIGN KEY (index_id) REFERENCES public.achievement_index(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."achievements"
  ADD CONSTRAINT "unique_user_achievement" UNIQUE (user_id, index_id);

ALTER TABLE "public"."equipment"
  ADD CONSTRAINT "equipment_character_id_fkey" FOREIGN KEY (character_id) REFERENCES public.character_stats(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."challenges"
  ADD CONSTRAINT "challenges_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."goal"
  ADD CONSTRAINT "goal_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."achievements"
  ADD CONSTRAINT "achievements_reward_id_fkey" FOREIGN KEY (reward_id) REFERENCES public.rewards(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."challenges"
  ADD CONSTRAINT "challenges_chall_reward_id_fkey" FOREIGN KEY (chall_reward_id) REFERENCES public.rewards(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."goal"
  ADD CONSTRAINT "goal_goal_rewardId_fkey" FOREIGN KEY (goal_reward_id) REFERENCES public.rewards(id);

ALTER TABLE "public"."character_stats"
  ADD CONSTRAINT "stats_skin_index_id_fkey" FOREIGN KEY (skin_index_id) REFERENCES public.skin_index(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."challenges"
  ADD CONSTRAINT "challenges_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."tasks"
  ADD CONSTRAINT "tasks_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id);

ALTER TABLE "public"."tasks"
  ADD CONSTRAINT "tasks_task_reward_id_fkey" FOREIGN KEY (task_reward_id) REFERENCES public.rewards(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."equipment"
  ADD CONSTRAINT "equipment_index_id_fkey" FOREIGN KEY (tool_index_id) REFERENCES public.tool_index(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."users"
  ADD CONSTRAINT "users_playerName_fkey" FOREIGN KEY ("playerName") REFERENCES public.character_stats("playerName") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."users"
  ADD CONSTRAINT "users_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public.character_stats(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."achievements"
  ADD CONSTRAINT "achievements_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."character_stats"
  ADD CONSTRAINT "character_stats_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."goal"
  ADD CONSTRAINT "goal_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."groups"
  ADD CONSTRAINT "groups_userId_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET DEFAULT;

ALTER TABLE "public"."rewards"
  ADD CONSTRAINT "rewards_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "public"."tasks"
  ADD CONSTRAINT "tasks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX idx_users_inner_id ON public.users USING btree (inner_id);

CREATE POLICY "Permitir lectura publica de achievement_index" ON "public"."achievement_index"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Gestionar mis logros obtenidos" ON "public"."achievements"
  FOR ALL
  TO "authenticated"
  USING ((user_id = public.get_current_user_id()));

CREATE POLICY "Gestionar mis propios desafios" ON "public"."challenges"
  FOR ALL
  TO "authenticated"
  USING ((user_id = public.get_current_user_id()));

CREATE POLICY "Modificar solo mis propios stats" ON "public"."character_stats"
  FOR UPDATE
  TO "authenticated"
  USING ((user_id = public.get_current_user_id()));

CREATE POLICY "Ver stats propios o de otros jugadores" ON "public"."character_stats"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Gestionar mi propio equipamiento" ON "public"."equipment"
  FOR ALL
  TO "authenticated"
  USING ((character_id IN ( SELECT character_stats.id
   FROM public.character_stats
  WHERE (character_stats.user_id = public.get_current_user_id()))));

CREATE POLICY "Gestionar mis propias metas" ON "public"."goal"
  FOR ALL
  TO "authenticated"
  USING ((user_id = public.get_current_user_id()));

CREATE POLICY "Ver y reclamar mis propias recompensas" ON "public"."rewards"
  FOR ALL
  TO "authenticated"
  USING ((user_id = public.get_current_user_id()));

CREATE POLICY "Permitir lectura publica de skin_index" ON "public"."skin_index"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Gestionar mis propias tareas" ON "public"."tasks"
  FOR ALL
  TO "authenticated"
  USING ((user_id = public.get_current_user_id()));

CREATE POLICY "Permitir lectura publica de tool_index" ON "public"."tool_index"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Usuarios pueden actualizar su propio perfil" ON "public"."users"
  FOR UPDATE
  TO "authenticated"
  USING ((inner_id = auth.uid()))
  WITH CHECK ((inner_id = auth.uid()));

CREATE POLICY "Usuarios pueden ver perfiles" ON "public"."users"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "inner_id_policy" ON "public"."users"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = inner_id));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

COMMENT ON COLUMN "public"."achievement_index"."created_at" IS 'Fecha creacion logro';

COMMENT ON COLUMN "public"."achievement_index"."description" IS 'Descripción genera del logro, indicando los requisitos de obtención';

COMMENT ON COLUMN "public"."achievement_index"."gold_reward" IS 'Recompensa innerente al logro en oro';

COMMENT ON COLUMN "public"."achievement_index"."name" IS 'Nombre del logro';

COMMENT ON COLUMN "public"."achievement_index"."tier" IS 'Tier del logro en función de su rareza';

COMMENT ON COLUMN "public"."achievement_index"."xp_reward" IS 'Recompensa innerente al logro en experiencia';

COMMENT ON COLUMN "public"."achievements"."acquired_at" IS 'Fecha de adquisición';

COMMENT ON COLUMN "public"."achievements"."reward_id" IS 'Descripción de la recompensa';

COMMENT ON COLUMN "public"."challenges"."chall_reward_id" IS 'Recompensa innerente al desafío';

COMMENT ON COLUMN "public"."challenges"."completed" IS 'Estado del desafío';

COMMENT ON COLUMN "public"."challenges"."created_at" IS 'Fecha de creación';

COMMENT ON COLUMN "public"."challenges"."description" IS 'Descripción del desafío';

COMMENT ON COLUMN "public"."challenges"."dificulty" IS 'Dificultad del desafío en función de los requisitos añadidos a la tarea';

COMMENT ON COLUMN "public"."challenges"."group_id" IS 'Identificador del grupo';

COMMENT ON COLUMN "public"."challenges"."name" IS 'Nombre del desafío';

COMMENT ON COLUMN "public"."challenges"."rating" IS 'Autoevalución del usuario del 1 al 10 en función de su desempeño en el desafío en cuestión';

COMMENT ON COLUMN "public"."challenges"."requirement" IS 'Requisito extra del desafío';

COMMENT ON COLUMN "public"."challenges"."task_id" IS 'Tareas asignada';

COMMENT ON COLUMN "public"."challenges"."user_id" IS 'Identificador del usuario ligado al desafío';

COMMENT ON COLUMN "public"."challenges"."visibility" IS 'Visibilidad del desafio';

COMMENT ON COLUMN "public"."character_stats"."class" IS 'Tipo de personaje';

COMMENT ON COLUMN "public"."character_stats"."gold" IS 'La moneda del juego, se pueden comprar amras, equipamiento y skins. Se obtien en recompensas';

COMMENT ON COLUMN "public"."character_stats"."hp" IS 'Vida, constituye la barra de salud. En un combate, cuando llega a 0, pierdes. Se incrementa con vida social y trabajo.';

COMMENT ON COLUMN "public"."character_stats"."id" IS 'Identificador de las estadísticas del personaje';

COMMENT ON COLUMN "public"."character_stats"."level" IS 'Nivel de progreso del jugador en su aventura. Todas las estadísticas se incrementan, especialmente la vida máxima';

COMMENT ON COLUMN "public"."character_stats"."playerName" IS 'Nombre del personaje que representa al jugador';

COMMENT ON COLUMN "public"."character_stats"."speed" IS 'Velocidad, decide quien comienza a atacar en un combate. Se incrementa mediante el deporte y el ocio.';

COMMENT ON COLUMN "public"."character_stats"."stamina" IS 'Estamina, constituye la barra de estamina, permite seguir atacando en combate repetidamente. Si está baja, el personaje usará el próximo turno para descansar. Se entrena con deporte y entrenamiento';

COMMENT ON COLUMN "public"."character_stats"."strength" IS 'Fuerza, en un combate dicta qué tan fuerte golpearás a tu adversario. Se potencia con entrenamiento y trabajo.';

COMMENT ON COLUMN "public"."character_stats"."wisdom" IS 'Representa el conocimiento del personaje. En un combate, potencia el ataque definitivo. Se mejora con trabajo y estudio';

COMMENT ON COLUMN "public"."character_stats"."xpCurrent" IS 'Experiencia acumulada del usuario para subir al próximo nivel';

COMMENT ON COLUMN "public"."character_stats"."xpTotal" IS 'Experiencia total ganada. Se obtiene en recompensas. Crucial para subir de nivel.';

COMMENT ON COLUMN "public"."equipment"."acquired_at" IS 'Fecha de adquisición';

COMMENT ON COLUMN "public"."equipment"."current_tool_tier" IS 'Tier de la herramienta en función de su calidad';

COMMENT ON COLUMN "public"."equipment"."current_upgrade_price" IS 'Precio al mejorar';

COMMENT ON COLUMN "public"."equipment"."stats" IS 'Estadísticas aportadas al juagador';

COMMENT ON COLUMN "public"."equipment"."type" IS 'Tipo de equipación';

COMMENT ON COLUMN "public"."goal"."completed" IS 'Estado de finalización';

COMMENT ON COLUMN "public"."goal"."end_date" IS 'Deadline del objetivo';

COMMENT ON COLUMN "public"."goal"."group_id" IS 'Identificador del grupo';

COMMENT ON COLUMN "public"."goal"."name" IS 'Nombre del objetivo';

COMMENT ON COLUMN "public"."goal"."rating" IS 'Autoevalución del usuario del 1 al 10 en función de su desempeño en el objetivo en cuestión';

COMMENT ON COLUMN "public"."goal"."visibility" IS 'Visibilidad del objetivo';

COMMENT ON COLUMN "public"."groups"."id" IS 'Identificador de los grupos de quehaceres';

COMMENT ON COLUMN "public"."groups"."user_id" IS 'Puntero ligado al usuario';

COMMENT ON COLUMN "public"."rewards"."claimed_at" IS 'Fecha de reclamación';

COMMENT ON COLUMN "public"."rewards"."user_id" IS 'Identificador del usuario ligado a la recompensa';

COMMENT ON COLUMN "public"."tasks"."activity_type" IS 'Tipo de actividad, puede ser una de 6: Entrenamiento, trabajo, estudio, deporte, vida social y ocio, cada una dando sus respectivas estadisticas';

COMMENT ON COLUMN "public"."tasks"."group_id" IS 'Identificador del grupo';

COMMENT ON COLUMN "public"."tasks"."icon" IS 'Icono (o emoji) de la tarea';

COMMENT ON COLUMN "public"."tasks"."name" IS 'Nombre de la tarea asignada';

COMMENT ON COLUMN "public"."tasks"."priority" IS 'Prioridad de la tarea';

COMMENT ON COLUMN "public"."tasks"."status" IS 'Estado, entre pendiente, en proceso, finalizada, completada o no completada';

COMMENT ON COLUMN "public"."tasks"."user_id" IS 'Identificador del usuario ligado a la tarea';

COMMENT ON COLUMN "public"."tasks"."visibility" IS 'Tipo de visibilidad de la tarea, pudiendo estar oculta, visible o borrada';

COMMENT ON COLUMN "public"."tool_index"."base_tool_tier" IS 'Tier base de la herramienta en función de su calidad al comprar';

COMMENT ON COLUMN "public"."tool_index"."base_upgrade_price" IS 'Precio inicial al mejorar';

COMMENT ON COLUMN "public"."tool_index"."max_level" IS 'Nivel maximo al que se puede subir';

COMMENT ON COLUMN "public"."tool_index"."purchase_price" IS 'Precio al comprar';

COMMENT ON COLUMN "public"."tool_index"."tool_type" IS 'Tipo de equipación';

COMMENT ON COLUMN "public"."tool_index"."upgrade_stat_buffs" IS 'Estadisticas otorgadas al mejorar un nivel';

COMMENT ON COLUMN "public"."users"."account_type" IS 'Plan de la cuenta contratado';

COMMENT ON COLUMN "public"."users"."created_at" IS 'Fecha de creación';

COMMENT ON COLUMN "public"."users"."email" IS 'Correo del usuario de la cuenta';

COMMENT ON COLUMN "public"."users"."id" IS 'Identificador de los usuarios en la BD';

COMMENT ON COLUMN "public"."users"."inner_id" IS 'Id interno ligado al auth de supabase';

COMMENT ON COLUMN "public"."users"."playerName" IS 'Nombre del personaje que representa al jugador';

COMMENT ON COLUMN "public"."users"."player_id" IS 'Id del jugador asociado al usuario';

COMMENT ON COLUMN "public"."users"."profile_url" IS 'Link para la foto de perfil';

COMMENT ON COLUMN "public"."users"."task_streak" IS 'Racha de tareas completadas del usuario';

COMMENT ON COLUMN "public"."users"."user_icon" IS 'Icono (o emoji) del jugador';

COMMENT ON COLUMN "public"."users"."xp_acc_boost" IS 'Bonus de experiencia de la cuenta por diferentes multiplicadores aplicados a su cuenta';

COMMENT ON TABLE "public"."achievement_index" IS 'Lista de todos los logros disponibles';

COMMENT ON TABLE "public"."achievements" IS 'Logros completados';

COMMENT ON TABLE "public"."challenges" IS 'Desafíos impuestos';

COMMENT ON TABLE "public"."character_stats" IS 'Estadísticas del jugador';

COMMENT ON TABLE "public"."equipment" IS 'Armas y herramientas del usuario';

COMMENT ON TABLE "public"."goal" IS 'Metas impuestas';

COMMENT ON TABLE "public"."groups" IS 'Grupos de tareas, desafios y metas';

COMMENT ON TABLE "public"."rewards" IS 'Recompensas de los desafios, tareas, logros y objetivos';

COMMENT ON TABLE "public"."skin_index" IS 'Tabla con todos los índices de las skins';

COMMENT ON TABLE "public"."tasks" IS 'Tareas del calendario';

COMMENT ON TABLE "public"."tool_index" IS 'Lista de herramientas';

COMMENT ON TABLE "public"."users" IS 'Los usuarios para iniciar sesión (login). CONTRASEÑAS EN AUTH';

GRANT EXECUTE ON FUNCTION "public"."get_current_user_id"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."get_current_user_id"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."get_current_user_id"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."get_current_user_id"() TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."rls_auto_enable"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "service_role";

REVOKE ALL ON SEQUENCE "public"."Example_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Example_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."Example_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Example_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."Example_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Example_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."Example_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."Example_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."achievements_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."achievements_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."achievements_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."achievements_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."achievements_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."achievements_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."achievements_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."achievements_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."challenges_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."challenges_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."challenges_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."challenges_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."challenges_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."challenges_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."challenges_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."challenges_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."equipment_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."equipment_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."equipment_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."equipment_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."equipment_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."equipment_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."equipment_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."equipment_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."goal_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."goal_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."goal_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."goal_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."goal_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."goal_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."goal_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."goal_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."groups_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."groups_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."groups_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."groups_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."groups_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."groups_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."groups_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."groups_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."index_archievment_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."index_archievment_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."index_archievment_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."index_archievment_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."index_archievment_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."index_archievment_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."index_archievment_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."index_archievment_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."rewards_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."rewards_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."rewards_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."rewards_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."rewards_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."rewards_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."rewards_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."rewards_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."skin_index_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."skin_index_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."skin_index_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."skin_index_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."skin_index_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."skin_index_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."skin_index_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."skin_index_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."stats_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."stats_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."stats_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."stats_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."stats_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."stats_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."stats_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."stats_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."tool_index_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tool_index_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."tool_index_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tool_index_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."tool_index_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tool_index_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."tool_index_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tool_index_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."usuarios_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."usuarios_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."usuarios_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."usuarios_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."usuarios_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."usuarios_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."usuarios_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."usuarios_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."achievement_index" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."achievement_index" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."achievement_index" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."achievement_index" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."achievements" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."achievements" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."achievements" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."achievements" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."challenges" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."challenges" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."challenges" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."challenges" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."character_stats" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."character_stats" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."character_stats" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."character_stats" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."equipment" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."equipment" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."equipment" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."equipment" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."goal" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."goal" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."goal" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."goal" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."groups" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."groups" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."groups" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."groups" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."rewards" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."rewards" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."rewards" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."rewards" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."skin_index" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."skin_index" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."skin_index" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."skin_index" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tasks" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."tasks" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tasks" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tasks" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tool_index" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."tool_index" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tool_index" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tool_index" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."users" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "service_role";

